# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ef16976c83dfccb42c39ee28c96d56ee684ff2ed92e2330066b74e4530762d430bbfc55c1315adf08b7c1e65cfdebc0de962cd9418d1ab7dd8fb30329ae28356

test:
  secret_key_base: 44ae90d386ca5da46bfe7ec9b5db6a1f81e83e828d2dd1cccced105659bc1fb8797c3cbb6a8e225e63f70b4ae8bb8bc0facad143a79805d07f150c418a70cf77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
